# Generated by Django 4.1.7 on 2023-03-28 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_interface', '0003_delete_bookingrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id_request', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код')),
                ('time_visit', models.DateTimeField()),
                ('number_persons', models.IntegerField(verbose_name='Количество человек')),
                ('note_user', models.CharField(max_length=4096, verbose_name='Примечание пользователя')),
                ('status', models.BooleanField()),
                ('id_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interface.place')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка на бронирование',
                'verbose_name_plural': 'Заявка на бронирование',
            },
        ),
    ]
