# Generated by Django 4.1.7 on 2023-03-27 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id_manager', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код менеджера')),
                ('login', models.CharField(max_length=32, verbose_name='Логин')),
                ('password', models.CharField(max_length=64, verbose_name='Пароль')),
                ('email', models.SlugField(max_length=320)),
                ('surname', models.CharField(max_length=43, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=16, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=20, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджер',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id_place', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер заведения')),
                ('name_place', models.CharField(max_length=64, verbose_name='Наименование заведения')),
                ('number_phone', models.CharField(help_text='Формат +*(***)-***-**-**', max_length=17, verbose_name='Номер телефона')),
                ('number_buld', models.IntegerField(verbose_name='Номер дома')),
                ('operating_mode', models.CharField(max_length=64, null=True)),
                ('live_music', models.BooleanField()),
                ('takeaway_food', models.BooleanField()),
                ('delivery', models.BooleanField()),
                ('summer_veranda', models.BooleanField()),
                ('menu_vegan', models.BooleanField()),
                ('visit_pet', models.BooleanField()),
                ('bus_lunch', models.BooleanField()),
                ('child_room', models.BooleanField()),
                ('features', models.JSONField()),
                ('url', models.SlugField(null=True)),
            ],
            options={
                'verbose_name': 'Заведения',
                'verbose_name_plural': 'Заведение',
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id_street', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код улицы')),
                ('name_street', models.CharField(max_length=64, verbose_name='Наименование улицы')),
            ],
            options={
                'verbose_name': 'Улица',
                'verbose_name_plural': 'Улица',
            },
        ),
        migrations.CreateModel(
            name='TypeKitchen',
            fields=[
                ('id_type', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер типа кухни')),
                ('name_type', models.CharField(max_length=64, verbose_name='Наименование типа')),
            ],
            options={
                'verbose_name': 'Тип кухни',
                'verbose_name_plural': 'Тип кухни',
            },
        ),
        migrations.CreateModel(
            name='TypePlace',
            fields=[
                ('id_type', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер типа заведения')),
                ('name_type', models.CharField(max_length=64, verbose_name='Наименование типа заведения')),
            ],
            options={
                'verbose_name': 'Тип заведения',
                'verbose_name_plural': 'Тип заведения',
            },
        ),
        migrations.CreateModel(
            name='Place_typeKitchen',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код')),
                ('id_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interface.place')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interface.typekitchen')),
            ],
            options={
                'verbose_name': 'Заведение_типКухни',
                'verbose_name_plural': 'Заведение_типКухни',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='id_street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interface.street'),
        ),
        migrations.AddField(
            model_name='place',
            name='id_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interface.typeplace'),
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id_favorites', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код')),
                ('id_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interface.place')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
            },
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id_request', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код')),
                ('time_visit', models.DateTimeField()),
                ('number_persons', models.IntegerField(verbose_name='Количество человек')),
                ('note_user', models.CharField(max_length=4096, verbose_name='Примечание пользователя')),
                ('status', models.BooleanField()),
                ('id_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interface.place')),
            ],
            options={
                'verbose_name': 'Заявка на бронирование',
                'verbose_name_plural': 'Заявка на бронирование',
            },
        ),
    ]
