# Generated by Django 4.1.7 on 2023-03-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
