# Generated by Django 4.1.7 on 2023-03-28 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0002_delete_favorites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingRequest',
        ),
    ]
