# Generated by Django 4.1.7 on 2023-03-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_abstractniyuser_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractniyuser',
            name='login',
        ),
        migrations.AlterField(
            model_name='abstractniyuser',
            name='username',
            field=models.CharField(blank=True, max_length=32, unique=True, verbose_name='Логин'),
        ),
    ]
