# Generated by Django 4.1.7 on 2023-03-27 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_interface', '0002_delete_favorites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id_favorites', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код')),
                ('page_url', models.URLField()),
                ('id_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interface.place')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
            },
        ),
    ]
