# Generated by Django 4.1.7 on 2023-03-28 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id_favorites', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код')),
                ('page_url', models.URLField()),
                ('id_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interface.place')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
            },
        ),
    ]
