# Generated by Django 4.1.7 on 2023-03-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0003_remove_favorites_page_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='id_favorites',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
